theme: jekyll-theme-minimal
remote_theme: jekyll/minima

plugins: jekyll-remote-theme

title: Md Asifur Rahman (he/him)
logo: /assests/img/pp.png
google_analytics: G-MDNNV2DYS6

url: "https://asifurrahman1.github.io/CV/"


# description: Graduate Research Assistant,<br><a href="https://www.wfu.edu/">WFU,</a> United States

# Department of Computer Science, <br>
# Wake Forest University, <br>
# North Carolina, United States, <br>
# [Email](mailto:rahmm21@wfu.edu) / [Website](https://www.cse.ruet.ac.bd/asifurrahman) / [LinkedIn](https://www.linkedin.com/in/asifur-rahman-33121892/) / [GitHub](https://github.com/asifurrahman1/) 
