theme: jekyll-theme-minimal
# title: CV- Md Asifur Rahman
logo: /assests/img/pp.png
# description: Md Asifur Rahman
# Department of Computer Science & Engineering, <br>
# Rajshahi University of Engineering & Technology (RUET), <br>
# Bangladesh, <br>
# [Email](mailto:asifurrahman1@gmail.com) / [Website](https://www.cse.ruet.ac.bd/asifurrahman) / [LinkedIn](https://www.linkedin.com/in/asifur-rahman-33121892/) / [GitHub](https://github.com/asifurrahman1/) 
