theme: jekyll-theme-minimal
remote_theme: jekyll/minima

environment: production

title: Md Asifur Rahman (he/him)
logo: /assests/img/pp.png

url: "https://asifurrahman1.github.io/CV/"

# Google Analytics
google_analytics: G-MDNNV2DYS6


# provider: "google-gtag"
# google:
#   tracking_id: "G-MDNNV2DYS6"
#   anonymize_ip: false # default


# description: Graduate Research Assistant,<br><a href="https://www.wfu.edu/">WFU,</a> United States

# Department of Computer Science, <br>
# Wake Forest University, <br>
# North Carolina, United States, <br>
# [Email](mailto:rahmm21@wfu.edu) / [Website](https://www.cse.ruet.ac.bd/asifurrahman) / [LinkedIn](https://www.linkedin.com/in/asifur-rahman-33121892/) / [GitHub](https://github.com/asifurrahman1/) 
